import { ThemeProvider } from "@/components/providers/ThemeProvider";
import "../globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en" suppressHydrationWarning>
   <body>
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
     {children}
    </ThemeProvider>
   </body>
  </html>
 );
}
